# Generated by Django 5.0.3 on 2024-03-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_following_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
