# Generated by Django 5.0.3 on 2024-03-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_comment_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='PostComment',
        ),
    ]
