# Generated by Django 5.0.3 on 2024-04-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
