# Generated by Django 5.0.3 on 2024-04-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_post_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='follower',
            new_name='user',
        ),
    ]
