# Generated by Django 5.0.3 on 2024-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alter_post_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
